export const UPDATE_TIME = 'UPDATE_TIME'
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR'

export const POSTS_RECEIVED = 'POSTS_RECEIVED'
export const POSTS_LOADING = 'POSTS_LOADING'
export const POSTS_ERROR = 'POSTS_ERROR'

export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'
export const COMMENTS_ERROR = 'COMMENTS_ERROR'
