export const UPDATE_TIME = 'UPDATE_TIME'
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR'

export const POSTS_RECEIVED = 'POSTS_RECEIVED'
export const POSTS_LOADING = 'POSTS_LOADING'
export const POSTS_ERROR = 'POSTS_ERROR'

export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'
export const COMMENTS_ERROR = 'COMMENTS_ERROR'

export const SET_SORT_FIELD = 'SET_SORT_FIELD';
export const SET_SORT_ASCENDING= 'SET_SORT_ASCENDING';

export const VOTING_COMPLETE = 'VOTING_COMPLETE';
export const VOTING_ERROR = 'VOTING_ERROR';
export const VOTING_LOADING = 'VOTING_LOADING';

export const DELETING_POST= 'DELETING_POST';
export const DELETE_POST_ERROR= 'DELETE_POST_ERROR';
export const DELETE_POST_COMPLETE= 'DELETE_POST_COMPLETE';

export const POST_DETAIL_RECEIVED = 'POST_DETAIL_RECEIVED';
export const POST_DETAIL_LOADING = 'POST_DETAIL_LOADING';
export const POST_DETAIL_ERROR = 'POST_DETAIL_ERROR';
export const POST_DETAIL_CLEAR = 'POST_DETAIL_CLEAR';

